name: 'CI: Pytest, Codecov and PyPI Publish'

on:
  # manual trigger
  workflow_dispatch:
  
  # pull requests
  pull_request:
    branches:
      - main
    paths:
      - 'aws-sso-manager/**'
      - 'tests/**'
      - 'poetry.lock'
      - 'pyproject.toml'

  # release
  release:
    types: [published]

jobs:
  
  # Build, test and upload codecov report
  python-test:
    name: pytest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
          cache: poetry

      - name: Install awsssomanager
        run: poetry install --no-interaction --no-ansi

      - name: Run Tests
        run: poetry run pytest --cov awsssomanager

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env: 
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python == 3.12 }}

  # Publish
  publish:
    needs: python-test
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          architecture: x64

      - name: Install Poetry
        run: pipx install poetry

      - name: Build and publish
        run: |
          poetry publish --build --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
